# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# ssh deploy ss
name: Node.js CI

on:
  push:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
     - name: SSH deploy
       uses: appleboy/ssh-action@master
       with:
          host: ${{ secrets.SSH_IP }}
          username:  ${{ secrets.SSH_USERNAME }}
          key:  ${{ secrets.SSH_KEY }}
          script: |
               cd /home/ubuntu/ && rm -rf /home/ubuntu/musician-app && git clone https://github.com/tawdebo/musician-app.git
               cd /home/ubuntu/musician-app/client
               npm install
               npm run build
               pm2 start npm -- start
               cd /home/ubuntu/musician-app  
               npm install
               npm run build
               pm2 start npm -- start
